// AUTO-GENERATED by scripts/prefetch-data.js - DO NOT EDIT
// Shops, brands, city-areas, locations, and countries are served from D1 at runtime.
// Only small static datasets remain as prefetched JSON files.

/* eslint-disable @typescript-eslint/no-explicit-any */

export const PREFETCH_TIMESTAMP = 1771317321491;

// Stats from last prefetch (for reference only):
// Regions: 9, Tags: 78, Events: 6, People: 12, News: 36
