// AUTO-GENERATED by scripts/prefetch-data.js - DO NOT EDIT
// This file is generated at build time and bundled into the deployment
// Cloudflare Workers don't have filesystem access, so data must be bundled
//
// This is a placeholder - run `npm run prefetch:prod` to populate with real data

import { Shop, Country, CityArea } from '@/lib/types';
import { Brand } from '@/lib/api/brands';

export const prefetchedShops: Shop[] = [];

export const prefetchedCountries: Country[] = [];

export const prefetchedCityAreas: CityArea[] = [];

export const prefetchedBrands: Brand[] = [];

export const PREFETCH_TIMESTAMP = 0;
