// AUTO-GENERATED by scripts/prefetch-data.js - DO NOT EDIT
// This is a PLACEHOLDER module - actual data is served from /data/*.json (CDN)
// We don't bundle data here to keep server function under Cloudflare's 25MB limit

/* eslint-disable @typescript-eslint/no-explicit-any */

// Empty arrays - data is fetched from static JSON files or Strapi API
export const prefetchedShops: any[] = [];
export const prefetchedCountries: any[] = [];
export const prefetchedCityAreas: any[] = [];
export const prefetchedBrands: any[] = [];

export const PREFETCH_TIMESTAMP = 1769655177477;

// Stats from last prefetch (for reference only):
// Shops: 766, Countries: 100, City Areas: 77, Brands: 528, Tags: 56
