/**
 * Pre-fetch static Strapi data before build
 *
 * Shops, brands, city-areas, locations, and countries are served from D1 at runtime.
 * This script only fetches the small static datasets that don't have D1 tables yet:
 * events, people, news-articles, tags, regions (~2.6MB total).
 */

const fs = require('fs');
const path = require('path');

const PUBLIC_DATA_DIR = path.join(__dirname, '../public/data');
const LIB_DATA_DIR = path.join(__dirname, '../lib/data');

// Always use production Strapi for prefetch
const STRAPI_URL = process.env.NEXT_PUBLIC_STRAPI_URL_PROD || 'https://helpful-oasis-8bb949e05d.strapiapp.com/api';
const STRAPI_TOKEN = process.env.NEXT_PUBLIC_STRAPI_TOKEN_PROD;

if (!STRAPI_TOKEN) {
  console.error('❌ NEXT_PUBLIC_STRAPI_TOKEN_PROD not set - cannot prefetch data. Aborting build.');
  process.exit(1);
}

// Skip prefetch if data already exists (avoids double-fetch during OpenNext build)
const eventsJsonPath = path.join(PUBLIC_DATA_DIR, 'events.json');
if (fs.existsSync(path.join(__dirname, '../.open-next-building')) && fs.existsSync(eventsJsonPath)) {
  console.log('⏭️  Skipping prefetch - data already exists (OpenNext inner build)');
  process.exit(0);
}

console.log('Using PRODUCTION Strapi\n');
console.log('Note: Shops, brands, city-areas, locations, and countries are served from D1.\n');

const headers = {
  'Content-Type': 'application/json',
  'Authorization': `Bearer ${STRAPI_TOKEN}`,
};

async function fetchWithRetry(url, options, retries = 5) {
  for (let attempt = 1; attempt <= retries; attempt++) {
    const response = await fetch(url, options);
    if (response.ok) return response;
    if (attempt < retries && response.status >= 500) {
      const delay = 3000 * attempt;
      console.log(`    Retry ${attempt}/${retries - 1} after ${response.status} (waiting ${delay / 1000}s)...`);
      await new Promise(r => setTimeout(r, delay));
      continue;
    }
    throw new Error(`${response.status} ${response.statusText}`);
  }
}

async function fetchAll(endpoint, params = '') {
  const url = `${STRAPI_URL}/${endpoint}?${params}&pagination[pageSize]=100`;
  console.log(`  Fetching ${endpoint}...`);

  const response = await fetchWithRetry(url, { headers });
  const json = await response.json();
  return json.data || [];
}

async function main() {
  console.log('Pre-fetching static Strapi data...\n');

  try {
    // Fetch regions
    console.log('1. Fetching regions...');
    const regions = await fetchAll('regions');
    console.log(`   ✓ ${regions.length} regions\n`);

    // Fetch tags
    console.log('2. Fetching tags...');
    const tags = await fetchAll('tags');
    console.log(`   ✓ ${tags.length} tags\n`);

    // Fetch events with city relation
    console.log('3. Fetching events...');
    const eventPopulate = 'populate=city&populate=image&populate=eventHostBrand.logo';
    const events = await fetchAll('events', eventPopulate);
    console.log(`   ✓ ${events.length} events\n`);

    // Fetch people with relations
    console.log('4. Fetching people...');
    const personPopulate = 'populate=photo&populate=locations&populate=person_picks.shop.featured_image&populate=person_picks.shop.brand.logo&populate=person_picks.shop.city_area&populate=affiliated_shop.featured_image&populate=affiliated_shop.brand.logo&populate=affiliated_shop.city_area&populate=affiliated_shop.location.country';
    const people = await fetchAll('people', personPopulate);
    console.log(`   ✓ ${people.length} people\n`);

    // Fetch news articles
    console.log('5. Fetching news articles...');
    const newsPopulate = 'populate=featured_image&populate=source.logo&populate=brands_mentioned.logo&populate=shops_mentioned.brand.logo&populate=shops_mentioned.featured_image&populate=shops_mentioned.location&populate=people_mentioned&populate=locations_mentioned';
    const newsArticles = await fetchAll('news-articles', newsPopulate);
    console.log(`   ✓ ${newsArticles.length} news articles\n`);

    // Write static JSON files for CDN
    console.log('6. Generating static JSON files for CDN...');
    if (!fs.existsSync(PUBLIC_DATA_DIR)) {
      fs.mkdirSync(PUBLIC_DATA_DIR, { recursive: true });
    }

    fs.writeFileSync(path.join(PUBLIC_DATA_DIR, 'regions.json'), JSON.stringify(regions));
    fs.writeFileSync(path.join(PUBLIC_DATA_DIR, 'tags.json'), JSON.stringify(tags));
    fs.writeFileSync(path.join(PUBLIC_DATA_DIR, 'events.json'), JSON.stringify(events));
    fs.writeFileSync(path.join(PUBLIC_DATA_DIR, 'people.json'), JSON.stringify(people));
    fs.writeFileSync(path.join(PUBLIC_DATA_DIR, 'news-articles.json'), JSON.stringify(newsArticles));

    console.log('   ✓ Generated public/data/*.json files\n');

    // Generate placeholder module
    console.log('7. Generating prefetched.ts...');
    if (!fs.existsSync(LIB_DATA_DIR)) {
      fs.mkdirSync(LIB_DATA_DIR, { recursive: true });
    }

    const moduleContent = `// AUTO-GENERATED by scripts/prefetch-data.js - DO NOT EDIT
// Shops, brands, city-areas, locations, and countries are served from D1 at runtime.
// Only small static datasets remain as prefetched JSON files.

/* eslint-disable @typescript-eslint/no-explicit-any */

export const PREFETCH_TIMESTAMP = ${Date.now()};

// Stats from last prefetch (for reference only):
// Regions: ${regions.length}, Tags: ${tags.length}, Events: ${events.length}, People: ${people.length}, News: ${newsArticles.length}
`;

    fs.writeFileSync(path.join(LIB_DATA_DIR, 'prefetched.ts'), moduleContent);
    console.log('   ✓ Generated lib/data/prefetched.ts\n');

    console.log('✅ All static data pre-fetched successfully!');
    console.log(`   Static files saved to ${PUBLIC_DATA_DIR}/`);

  } catch (error) {
    console.error('❌ Error pre-fetching data:', error.message);

    // If existing static data files are present, continue the build with stale data
    if (fs.existsSync(path.join(PUBLIC_DATA_DIR, 'events.json'))) {
      console.log('⚠️  Using existing static data files (may be stale). Build will continue.');
      console.log('   D1 serves shops/brands/locations/countries/city-areas at runtime.');
    } else {
      console.error('❌ No existing data files found. Cannot continue build.');
      process.exit(1);
    }
  }
}

main();
